<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-13LQO7QE" ignored="1" name="AlwaysRun Test" tests="3" failures="1" timestamp="2020-06-17T10:02:42 IST" time="0.009" errors="0">
  <testcase name="Begin" time="0.001" classname="testnglearning_youtubechannel.Hindi_AlwaysRun">
    <failure type="java.lang.AssertionError" message="We are failing this test case">
      <![CDATA[java.lang.AssertionError: We are failing this test case
at testnglearning_youtubechannel.Hindi_AlwaysRun.Begin(Hindi_AlwaysRun.java:14)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Begin -->
  <testcase name="Ready" time="0.001" classname="testnglearning_youtubechannel.Hindi_AlwaysRun"/>
  <testcase name="Steady" time="0.001" classname="testnglearning_youtubechannel.Hindi_AlwaysRun"/>
  <testcase name="Go" time="0.0" classname="testnglearning_youtubechannel.Hindi_AlwaysRun">
    <ignored/>
  </testcase> <!-- Go -->
</testsuite> <!-- AlwaysRun Test -->
